/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InstructionsRouteImport } from './routes/instructions'
import { Route as IzprateniRouteImport } from './routes/izprateni'
import { Route as IzvanBulgariaRouteImport } from './routes/izvan-bulgaria'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as PotvardiRouteImport } from './routes/potvardi'
import { Route as PrivacyNoticeRouteImport } from './routes/privacy-notice'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ProtokolRouteImport } from './routes/protokol'
import { Route as SignalRouteImport } from './routes/signal'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VhodRouteImport } from './routes/vhod'
import { Route as ZnachkaRouteImport } from './routes/znachka'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccessRouteImport } from './routes/admin/access'
import { Route as AdminSectionsRouteImport } from './routes/admin/sections'
import { Route as AdminSignupsRouteImport } from './routes/admin/signups'
import { Route as IzprateniIdRouteImport } from './routes/izprateni.$id'
import { Route as PokanaCodeRouteImport } from './routes/pokana.$code'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as RCodeRouteImport } from './routes/r.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionsRoute = InstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const IzprateniRoute = IzprateniRouteImport.update({
  id: '/izprateni',
  path: '/izprateni',
  getParentRoute: () => rootRouteImport,
} as any)
const IzvanBulgariaRoute = IzvanBulgariaRouteImport.update({
  id: '/izvan-bulgaria',
  path: '/izvan-bulgaria',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const PotvardiRoute = PotvardiRouteImport.update({
  id: '/potvardi',
  path: '/potvardi',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyNoticeRoute = PrivacyNoticeRouteImport.update({
  id: '/privacy-notice',
  path: '/privacy-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtokolRoute = ProtokolRouteImport.update({
  id: '/protokol',
  path: '/protokol',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalRoute = SignalRouteImport.update({
  id: '/signal',
  path: '/signal',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VhodRoute = VhodRouteImport.update({
  id: '/vhod',
  path: '/vhod',
  getParentRoute: () => rootRouteImport,
} as any)
const ZnachkaRoute = ZnachkaRouteImport.update({
  id: '/znachka',
  path: '/znachka',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSectionsRoute = AdminSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSignupsRoute = AdminSignupsRouteImport.update({
  id: '/signups',
  path: '/signups',
  getParentRoute: () => AdminRouteRoute,
} as any)
const IzprateniIdRoute = IzprateniIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IzprateniRoute,
} as any)
const PokanaCodeRoute = PokanaCodeRouteImport.update({
  id: '/pokana/$code',
  path: '/pokana/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PostsRoute,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/instructions': typeof InstructionsRoute
  '/izprateni': typeof IzprateniRouteWithChildren
  '/izvan-bulgaria': typeof IzvanBulgariaRoute
  '/kontakt': typeof KontaktRoute
  '/news': typeof NewsRoute
  '/posts': typeof PostsRouteWithChildren
  '/potvardi': typeof PotvardiRoute
  '/privacy-notice': typeof PrivacyNoticeRoute
  '/profil': typeof ProfilRoute
  '/protokol': typeof ProtokolRoute
  '/signal': typeof SignalRoute
  '/signup': typeof SignupRoute
  '/vhod': typeof VhodRoute
  '/znachka': typeof ZnachkaRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/signups': typeof AdminSignupsRoute
  '/izprateni/$id': typeof IzprateniIdRoute
  '/pokana/$code': typeof PokanaCodeRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/r/$code': typeof RCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/instructions': typeof InstructionsRoute
  '/izprateni': typeof IzprateniRouteWithChildren
  '/izvan-bulgaria': typeof IzvanBulgariaRoute
  '/kontakt': typeof KontaktRoute
  '/news': typeof NewsRoute
  '/potvardi': typeof PotvardiRoute
  '/privacy-notice': typeof PrivacyNoticeRoute
  '/profil': typeof ProfilRoute
  '/protokol': typeof ProtokolRoute
  '/signal': typeof SignalRoute
  '/signup': typeof SignupRoute
  '/vhod': typeof VhodRoute
  '/znachka': typeof ZnachkaRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/signups': typeof AdminSignupsRoute
  '/izprateni/$id': typeof IzprateniIdRoute
  '/pokana/$code': typeof PokanaCodeRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/r/$code': typeof RCodeRoute
  '/admin': typeof AdminIndexRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/instructions': typeof InstructionsRoute
  '/izprateni': typeof IzprateniRouteWithChildren
  '/izvan-bulgaria': typeof IzvanBulgariaRoute
  '/kontakt': typeof KontaktRoute
  '/news': typeof NewsRoute
  '/posts': typeof PostsRouteWithChildren
  '/potvardi': typeof PotvardiRoute
  '/privacy-notice': typeof PrivacyNoticeRoute
  '/profil': typeof ProfilRoute
  '/protokol': typeof ProtokolRoute
  '/signal': typeof SignalRoute
  '/signup': typeof SignupRoute
  '/vhod': typeof VhodRoute
  '/znachka': typeof ZnachkaRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/signups': typeof AdminSignupsRoute
  '/izprateni/$id': typeof IzprateniIdRoute
  '/pokana/$code': typeof PokanaCodeRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/r/$code': typeof RCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/faq'
    | '/instructions'
    | '/izprateni'
    | '/izvan-bulgaria'
    | '/kontakt'
    | '/news'
    | '/posts'
    | '/potvardi'
    | '/privacy-notice'
    | '/profil'
    | '/protokol'
    | '/signal'
    | '/signup'
    | '/vhod'
    | '/znachka'
    | '/admin/access'
    | '/admin/sections'
    | '/admin/signups'
    | '/izprateni/$id'
    | '/pokana/$code'
    | '/posts/$slug'
    | '/r/$code'
    | '/admin/'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/instructions'
    | '/izprateni'
    | '/izvan-bulgaria'
    | '/kontakt'
    | '/news'
    | '/potvardi'
    | '/privacy-notice'
    | '/profil'
    | '/protokol'
    | '/signal'
    | '/signup'
    | '/vhod'
    | '/znachka'
    | '/admin/access'
    | '/admin/sections'
    | '/admin/signups'
    | '/izprateni/$id'
    | '/pokana/$code'
    | '/posts/$slug'
    | '/r/$code'
    | '/admin'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/faq'
    | '/instructions'
    | '/izprateni'
    | '/izvan-bulgaria'
    | '/kontakt'
    | '/news'
    | '/posts'
    | '/potvardi'
    | '/privacy-notice'
    | '/profil'
    | '/protokol'
    | '/signal'
    | '/signup'
    | '/vhod'
    | '/znachka'
    | '/admin/access'
    | '/admin/sections'
    | '/admin/signups'
    | '/izprateni/$id'
    | '/pokana/$code'
    | '/posts/$slug'
    | '/r/$code'
    | '/admin/'
    | '/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  InstructionsRoute: typeof InstructionsRoute
  IzprateniRoute: typeof IzprateniRouteWithChildren
  IzvanBulgariaRoute: typeof IzvanBulgariaRoute
  KontaktRoute: typeof KontaktRoute
  NewsRoute: typeof NewsRoute
  PostsRoute: typeof PostsRouteWithChildren
  PotvardiRoute: typeof PotvardiRoute
  PrivacyNoticeRoute: typeof PrivacyNoticeRoute
  ProfilRoute: typeof ProfilRoute
  ProtokolRoute: typeof ProtokolRoute
  SignalRoute: typeof SignalRoute
  SignupRoute: typeof SignupRoute
  VhodRoute: typeof VhodRoute
  ZnachkaRoute: typeof ZnachkaRoute
  PokanaCodeRoute: typeof PokanaCodeRoute
  RCodeRoute: typeof RCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructions': {
      id: '/instructions'
      path: '/instructions'
      fullPath: '/instructions'
      preLoaderRoute: typeof InstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/izprateni': {
      id: '/izprateni'
      path: '/izprateni'
      fullPath: '/izprateni'
      preLoaderRoute: typeof IzprateniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/izvan-bulgaria': {
      id: '/izvan-bulgaria'
      path: '/izvan-bulgaria'
      fullPath: '/izvan-bulgaria'
      preLoaderRoute: typeof IzvanBulgariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/potvardi': {
      id: '/potvardi'
      path: '/potvardi'
      fullPath: '/potvardi'
      preLoaderRoute: typeof PotvardiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-notice': {
      id: '/privacy-notice'
      path: '/privacy-notice'
      fullPath: '/privacy-notice'
      preLoaderRoute: typeof PrivacyNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protokol': {
      id: '/protokol'
      path: '/protokol'
      fullPath: '/protokol'
      preLoaderRoute: typeof ProtokolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal': {
      id: '/signal'
      path: '/signal'
      fullPath: '/signal'
      preLoaderRoute: typeof SignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vhod': {
      id: '/vhod'
      path: '/vhod'
      fullPath: '/vhod'
      preLoaderRoute: typeof VhodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/znachka': {
      id: '/znachka'
      path: '/znachka'
      fullPath: '/znachka'
      preLoaderRoute: typeof ZnachkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sections': {
      id: '/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AdminSectionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/signups': {
      id: '/admin/signups'
      path: '/signups'
      fullPath: '/admin/signups'
      preLoaderRoute: typeof AdminSignupsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/izprateni/$id': {
      id: '/izprateni/$id'
      path: '/$id'
      fullPath: '/izprateni/$id'
      preLoaderRoute: typeof IzprateniIdRouteImport
      parentRoute: typeof IzprateniRoute
    }
    '/pokana/$code': {
      id: '/pokana/$code'
      path: '/pokana/$code'
      fullPath: '/pokana/$code'
      preLoaderRoute: typeof PokanaCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof PostsRoute
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminSectionsRoute: typeof AdminSectionsRoute
  AdminSignupsRoute: typeof AdminSignupsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminSectionsRoute: AdminSectionsRoute,
  AdminSignupsRoute: AdminSignupsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface IzprateniRouteChildren {
  IzprateniIdRoute: typeof IzprateniIdRoute
}

const IzprateniRouteChildren: IzprateniRouteChildren = {
  IzprateniIdRoute: IzprateniIdRoute,
}

const IzprateniRouteWithChildren = IzprateniRoute._addFileChildren(
  IzprateniRouteChildren,
)

interface PostsRouteChildren {
  PostsSlugRoute: typeof PostsSlugRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsSlugRoute: PostsSlugRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  InstructionsRoute: InstructionsRoute,
  IzprateniRoute: IzprateniRouteWithChildren,
  IzvanBulgariaRoute: IzvanBulgariaRoute,
  KontaktRoute: KontaktRoute,
  NewsRoute: NewsRoute,
  PostsRoute: PostsRouteWithChildren,
  PotvardiRoute: PotvardiRoute,
  PrivacyNoticeRoute: PrivacyNoticeRoute,
  ProfilRoute: ProfilRoute,
  ProtokolRoute: ProtokolRoute,
  SignalRoute: SignalRoute,
  SignupRoute: SignupRoute,
  VhodRoute: VhodRoute,
  ZnachkaRoute: ZnachkaRoute,
  PokanaCodeRoute: PokanaCodeRoute,
  RCodeRoute: RCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
