/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as InstructionsRouteImport } from './routes/instructions'
import { Route as IzprateniRouteImport } from './routes/izprateni'
import { Route as IzvanBulgariaRouteImport } from './routes/izvan-bulgaria'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PrivacyNoticeRouteImport } from './routes/privacy-notice'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ProtokolRouteImport } from './routes/protokol'
import { Route as SignalRouteImport } from './routes/signal'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VhodRouteImport } from './routes/vhod'
import { Route as ZnachkaRouteImport } from './routes/znachka'
import { Route as IzprateniIdRouteImport } from './routes/izprateni.$id'
import { Route as PokanaCodeRouteImport } from './routes/pokana.$code'
import { Route as RCodeRouteImport } from './routes/r.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionsRoute = InstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const IzprateniRoute = IzprateniRouteImport.update({
  id: '/izprateni',
  path: '/izprateni',
  getParentRoute: () => rootRouteImport,
} as any)
const IzvanBulgariaRoute = IzvanBulgariaRouteImport.update({
  id: '/izvan-bulgaria',
  path: '/izvan-bulgaria',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyNoticeRoute = PrivacyNoticeRouteImport.update({
  id: '/privacy-notice',
  path: '/privacy-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtokolRoute = ProtokolRouteImport.update({
  id: '/protokol',
  path: '/protokol',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalRoute = SignalRouteImport.update({
  id: '/signal',
  path: '/signal',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VhodRoute = VhodRouteImport.update({
  id: '/vhod',
  path: '/vhod',
  getParentRoute: () => rootRouteImport,
} as any)
const ZnachkaRoute = ZnachkaRouteImport.update({
  id: '/znachka',
  path: '/znachka',
  getParentRoute: () => rootRouteImport,
} as any)
const IzprateniIdRoute = IzprateniIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IzprateniRoute,
} as any)
const PokanaCodeRoute = PokanaCodeRouteImport.update({
  id: '/pokana/$code',
  path: '/pokana/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/instructions': typeof InstructionsRoute
  '/izprateni': typeof IzprateniRouteWithChildren
  '/izvan-bulgaria': typeof IzvanBulgariaRoute
  '/news': typeof NewsRoute
  '/privacy-notice': typeof PrivacyNoticeRoute
  '/profil': typeof ProfilRoute
  '/protokol': typeof ProtokolRoute
  '/signal': typeof SignalRoute
  '/signup': typeof SignupRoute
  '/vhod': typeof VhodRoute
  '/znachka': typeof ZnachkaRoute
  '/izprateni/$id': typeof IzprateniIdRoute
  '/pokana/$code': typeof PokanaCodeRoute
  '/r/$code': typeof RCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/instructions': typeof InstructionsRoute
  '/izprateni': typeof IzprateniRouteWithChildren
  '/izvan-bulgaria': typeof IzvanBulgariaRoute
  '/news': typeof NewsRoute
  '/privacy-notice': typeof PrivacyNoticeRoute
  '/profil': typeof ProfilRoute
  '/protokol': typeof ProtokolRoute
  '/signal': typeof SignalRoute
  '/signup': typeof SignupRoute
  '/vhod': typeof VhodRoute
  '/znachka': typeof ZnachkaRoute
  '/izprateni/$id': typeof IzprateniIdRoute
  '/pokana/$code': typeof PokanaCodeRoute
  '/r/$code': typeof RCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/instructions': typeof InstructionsRoute
  '/izprateni': typeof IzprateniRouteWithChildren
  '/izvan-bulgaria': typeof IzvanBulgariaRoute
  '/news': typeof NewsRoute
  '/privacy-notice': typeof PrivacyNoticeRoute
  '/profil': typeof ProfilRoute
  '/protokol': typeof ProtokolRoute
  '/signal': typeof SignalRoute
  '/signup': typeof SignupRoute
  '/vhod': typeof VhodRoute
  '/znachka': typeof ZnachkaRoute
  '/izprateni/$id': typeof IzprateniIdRoute
  '/pokana/$code': typeof PokanaCodeRoute
  '/r/$code': typeof RCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/instructions'
    | '/izprateni'
    | '/izvan-bulgaria'
    | '/news'
    | '/privacy-notice'
    | '/profil'
    | '/protokol'
    | '/signal'
    | '/signup'
    | '/vhod'
    | '/znachka'
    | '/izprateni/$id'
    | '/pokana/$code'
    | '/r/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/instructions'
    | '/izprateni'
    | '/izvan-bulgaria'
    | '/news'
    | '/privacy-notice'
    | '/profil'
    | '/protokol'
    | '/signal'
    | '/signup'
    | '/vhod'
    | '/znachka'
    | '/izprateni/$id'
    | '/pokana/$code'
    | '/r/$code'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/instructions'
    | '/izprateni'
    | '/izvan-bulgaria'
    | '/news'
    | '/privacy-notice'
    | '/profil'
    | '/protokol'
    | '/signal'
    | '/signup'
    | '/vhod'
    | '/znachka'
    | '/izprateni/$id'
    | '/pokana/$code'
    | '/r/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InstructionsRoute: typeof InstructionsRoute
  IzprateniRoute: typeof IzprateniRouteWithChildren
  IzvanBulgariaRoute: typeof IzvanBulgariaRoute
  NewsRoute: typeof NewsRoute
  PrivacyNoticeRoute: typeof PrivacyNoticeRoute
  ProfilRoute: typeof ProfilRoute
  ProtokolRoute: typeof ProtokolRoute
  SignalRoute: typeof SignalRoute
  SignupRoute: typeof SignupRoute
  VhodRoute: typeof VhodRoute
  ZnachkaRoute: typeof ZnachkaRoute
  PokanaCodeRoute: typeof PokanaCodeRoute
  RCodeRoute: typeof RCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructions': {
      id: '/instructions'
      path: '/instructions'
      fullPath: '/instructions'
      preLoaderRoute: typeof InstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/izprateni': {
      id: '/izprateni'
      path: '/izprateni'
      fullPath: '/izprateni'
      preLoaderRoute: typeof IzprateniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/izvan-bulgaria': {
      id: '/izvan-bulgaria'
      path: '/izvan-bulgaria'
      fullPath: '/izvan-bulgaria'
      preLoaderRoute: typeof IzvanBulgariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-notice': {
      id: '/privacy-notice'
      path: '/privacy-notice'
      fullPath: '/privacy-notice'
      preLoaderRoute: typeof PrivacyNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protokol': {
      id: '/protokol'
      path: '/protokol'
      fullPath: '/protokol'
      preLoaderRoute: typeof ProtokolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal': {
      id: '/signal'
      path: '/signal'
      fullPath: '/signal'
      preLoaderRoute: typeof SignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vhod': {
      id: '/vhod'
      path: '/vhod'
      fullPath: '/vhod'
      preLoaderRoute: typeof VhodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/znachka': {
      id: '/znachka'
      path: '/znachka'
      fullPath: '/znachka'
      preLoaderRoute: typeof ZnachkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/izprateni/$id': {
      id: '/izprateni/$id'
      path: '/$id'
      fullPath: '/izprateni/$id'
      preLoaderRoute: typeof IzprateniIdRouteImport
      parentRoute: typeof IzprateniRoute
    }
    '/pokana/$code': {
      id: '/pokana/$code'
      path: '/pokana/$code'
      fullPath: '/pokana/$code'
      preLoaderRoute: typeof PokanaCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IzprateniRouteChildren {
  IzprateniIdRoute: typeof IzprateniIdRoute
}

const IzprateniRouteChildren: IzprateniRouteChildren = {
  IzprateniIdRoute: IzprateniIdRoute,
}

const IzprateniRouteWithChildren = IzprateniRoute._addFileChildren(
  IzprateniRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InstructionsRoute: InstructionsRoute,
  IzprateniRoute: IzprateniRouteWithChildren,
  IzvanBulgariaRoute: IzvanBulgariaRoute,
  NewsRoute: NewsRoute,
  PrivacyNoticeRoute: PrivacyNoticeRoute,
  ProfilRoute: ProfilRoute,
  ProtokolRoute: ProtokolRoute,
  SignalRoute: SignalRoute,
  SignupRoute: SignupRoute,
  VhodRoute: VhodRoute,
  ZnachkaRoute: ZnachkaRoute,
  PokanaCodeRoute: PokanaCodeRoute,
  RCodeRoute: RCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
